services:
  web:
    build: .
    command: python app.py
    image: moolah-trading-web
    ports:
      - '8000:8000'
    env_file:
      - .env
  watcher:
    build: .
    image: moolah-trading-watcher
    command: python watch_orders.py
    env_file:
      - .env
