services:
  web:
    build: .
    command: poetry run python app.py
    ports:
      - '8000:8000'
    env_file:
      - .env
  watcher:
    build: .
    command: poetry run python watch_orders.py
    env_file:
      - .env